remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: ERS Agent Downloads
description: Download the Easy Remote System Agent for your platform
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/forewall/ers-release
